// Generated by gencpp from file commu_wrapper/CommULook.msg
// DO NOT EDIT!


#ifndef COMMU_WRAPPER_MESSAGE_COMMULOOK_H
#define COMMU_WRAPPER_MESSAGE_COMMULOOK_H

#include <ros/service_traits.h>


#include <commu_wrapper/CommULookRequest.h>
#include <commu_wrapper/CommULookResponse.h>


namespace commu_wrapper
{

struct CommULook
{

typedef CommULookRequest Request;
typedef CommULookResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CommULook
} // namespace commu_wrapper


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::commu_wrapper::CommULook > {
  static const char* value()
  {
    return "f140a05a390d4967a567a474c5dfde3f";
  }

  static const char* value(const ::commu_wrapper::CommULook&) { return value(); }
};

template<>
struct DataType< ::commu_wrapper::CommULook > {
  static const char* value()
  {
    return "commu_wrapper/CommULook";
  }

  static const char* value(const ::commu_wrapper::CommULook&) { return value(); }
};


// service_traits::MD5Sum< ::commu_wrapper::CommULookRequest> should match 
// service_traits::MD5Sum< ::commu_wrapper::CommULook > 
template<>
struct MD5Sum< ::commu_wrapper::CommULookRequest>
{
  static const char* value()
  {
    return MD5Sum< ::commu_wrapper::CommULook >::value();
  }
  static const char* value(const ::commu_wrapper::CommULookRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::commu_wrapper::CommULookRequest> should match 
// service_traits::DataType< ::commu_wrapper::CommULook > 
template<>
struct DataType< ::commu_wrapper::CommULookRequest>
{
  static const char* value()
  {
    return DataType< ::commu_wrapper::CommULook >::value();
  }
  static const char* value(const ::commu_wrapper::CommULookRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::commu_wrapper::CommULookResponse> should match 
// service_traits::MD5Sum< ::commu_wrapper::CommULook > 
template<>
struct MD5Sum< ::commu_wrapper::CommULookResponse>
{
  static const char* value()
  {
    return MD5Sum< ::commu_wrapper::CommULook >::value();
  }
  static const char* value(const ::commu_wrapper::CommULookResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::commu_wrapper::CommULookResponse> should match 
// service_traits::DataType< ::commu_wrapper::CommULook > 
template<>
struct DataType< ::commu_wrapper::CommULookResponse>
{
  static const char* value()
  {
    return DataType< ::commu_wrapper::CommULook >::value();
  }
  static const char* value(const ::commu_wrapper::CommULookResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMU_WRAPPER_MESSAGE_COMMULOOK_H
