// Generated by gencpp from file commu_wrapper/CommUUtterResponse.msg
// DO NOT EDIT!


#ifndef COMMU_WRAPPER_MESSAGE_COMMUUTTERRESPONSE_H
#define COMMU_WRAPPER_MESSAGE_COMMUUTTERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace commu_wrapper
{
template <class ContainerAllocator>
struct CommUUtterResponse_
{
  typedef CommUUtterResponse_<ContainerAllocator> Type;

  CommUUtterResponse_()
    : success(false)  {
    }
  CommUUtterResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;




  typedef boost::shared_ptr< ::commu_wrapper::CommUUtterResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::commu_wrapper::CommUUtterResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CommUUtterResponse_

typedef ::commu_wrapper::CommUUtterResponse_<std::allocator<void> > CommUUtterResponse;

typedef boost::shared_ptr< ::commu_wrapper::CommUUtterResponse > CommUUtterResponsePtr;
typedef boost::shared_ptr< ::commu_wrapper::CommUUtterResponse const> CommUUtterResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::commu_wrapper::CommUUtterResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::commu_wrapper::CommUUtterResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace commu_wrapper

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::commu_wrapper::CommUUtterResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::commu_wrapper::CommUUtterResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commu_wrapper::CommUUtterResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commu_wrapper::CommUUtterResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commu_wrapper::CommUUtterResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commu_wrapper::CommUUtterResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::commu_wrapper::CommUUtterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::commu_wrapper::CommUUtterResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::commu_wrapper::CommUUtterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "commu_wrapper/CommUUtterResponse";
  }

  static const char* value(const ::commu_wrapper::CommUUtterResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::commu_wrapper::CommUUtterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
bool success\n\
\n\
";
  }

  static const char* value(const ::commu_wrapper::CommUUtterResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::commu_wrapper::CommUUtterResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommUUtterResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::commu_wrapper::CommUUtterResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::commu_wrapper::CommUUtterResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMU_WRAPPER_MESSAGE_COMMUUTTERRESPONSE_H
