// Generated by gencpp from file commu_helper/BoundingBox.msg
// DO NOT EDIT!


#ifndef COMMU_HELPER_MESSAGE_BOUNDINGBOX_H
#define COMMU_HELPER_MESSAGE_BOUNDINGBOX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace commu_helper
{
template <class ContainerAllocator>
struct BoundingBox_
{
  typedef BoundingBox_<ContainerAllocator> Type;

  BoundingBox_()
    : x_min(0.0)
    , y_min(0.0)
    , x_size(0.0)
    , y_size(0.0)  {
    }
  BoundingBox_(const ContainerAllocator& _alloc)
    : x_min(0.0)
    , y_min(0.0)
    , x_size(0.0)
    , y_size(0.0)  {
  (void)_alloc;
    }



   typedef double _x_min_type;
  _x_min_type x_min;

   typedef double _y_min_type;
  _y_min_type y_min;

   typedef double _x_size_type;
  _x_size_type x_size;

   typedef double _y_size_type;
  _y_size_type y_size;




  typedef boost::shared_ptr< ::commu_helper::BoundingBox_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::commu_helper::BoundingBox_<ContainerAllocator> const> ConstPtr;

}; // struct BoundingBox_

typedef ::commu_helper::BoundingBox_<std::allocator<void> > BoundingBox;

typedef boost::shared_ptr< ::commu_helper::BoundingBox > BoundingBoxPtr;
typedef boost::shared_ptr< ::commu_helper::BoundingBox const> BoundingBoxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::commu_helper::BoundingBox_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::commu_helper::BoundingBox_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace commu_helper

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'commu_helper': ['/home/maurice/catkin_ws/src/commu_helper/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::commu_helper::BoundingBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::commu_helper::BoundingBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commu_helper::BoundingBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commu_helper::BoundingBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commu_helper::BoundingBox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commu_helper::BoundingBox_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::commu_helper::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49841939163c4125050016679dd0cb15";
  }

  static const char* value(const ::commu_helper::BoundingBox_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49841939163c4125ULL;
  static const uint64_t static_value2 = 0x050016679dd0cb15ULL;
};

template<class ContainerAllocator>
struct DataType< ::commu_helper::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "commu_helper/BoundingBox";
  }

  static const char* value(const ::commu_helper::BoundingBox_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::commu_helper::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A simple 2d bounding box message\n\
\n\
float64 x_min\n\
float64 y_min\n\
float64 x_size\n\
float64 y_size\n\
";
  }

  static const char* value(const ::commu_helper::BoundingBox_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::commu_helper::BoundingBox_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_min);
      stream.next(m.y_min);
      stream.next(m.x_size);
      stream.next(m.y_size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoundingBox_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::commu_helper::BoundingBox_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::commu_helper::BoundingBox_<ContainerAllocator>& v)
  {
    s << indent << "x_min: ";
    Printer<double>::stream(s, indent + "  ", v.x_min);
    s << indent << "y_min: ";
    Printer<double>::stream(s, indent + "  ", v.y_min);
    s << indent << "x_size: ";
    Printer<double>::stream(s, indent + "  ", v.x_size);
    s << indent << "y_size: ";
    Printer<double>::stream(s, indent + "  ", v.y_size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMU_HELPER_MESSAGE_BOUNDINGBOX_H
