// Generated by gencpp from file commu_helper/ClassifiedObject.msg
// DO NOT EDIT!


#ifndef COMMU_HELPER_MESSAGE_CLASSIFIEDOBJECT_H
#define COMMU_HELPER_MESSAGE_CLASSIFIEDOBJECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/String.h>
#include <commu_helper/BoundingBox.h>

namespace commu_helper
{
template <class ContainerAllocator>
struct ClassifiedObject_
{
  typedef ClassifiedObject_<ContainerAllocator> Type;

  ClassifiedObject_()
    : header()
    , score(0.0)
    , label()
    , bbox()  {
    }
  ClassifiedObject_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , score(0.0)
    , label(_alloc)
    , bbox(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _score_type;
  _score_type score;

   typedef  ::std_msgs::String_<ContainerAllocator>  _label_type;
  _label_type label;

   typedef  ::commu_helper::BoundingBox_<ContainerAllocator>  _bbox_type;
  _bbox_type bbox;




  typedef boost::shared_ptr< ::commu_helper::ClassifiedObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::commu_helper::ClassifiedObject_<ContainerAllocator> const> ConstPtr;

}; // struct ClassifiedObject_

typedef ::commu_helper::ClassifiedObject_<std::allocator<void> > ClassifiedObject;

typedef boost::shared_ptr< ::commu_helper::ClassifiedObject > ClassifiedObjectPtr;
typedef boost::shared_ptr< ::commu_helper::ClassifiedObject const> ClassifiedObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::commu_helper::ClassifiedObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::commu_helper::ClassifiedObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace commu_helper

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'commu_helper': ['/home/maurice/catkin_ws/src/commu_helper/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::commu_helper::ClassifiedObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::commu_helper::ClassifiedObject_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commu_helper::ClassifiedObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commu_helper::ClassifiedObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commu_helper::ClassifiedObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commu_helper::ClassifiedObject_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::commu_helper::ClassifiedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b202e404f3f0348d886cbf8b47d95083";
  }

  static const char* value(const ::commu_helper::ClassifiedObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb202e404f3f0348dULL;
  static const uint64_t static_value2 = 0x886cbf8b47d95083ULL;
};

template<class ContainerAllocator>
struct DataType< ::commu_helper::ClassifiedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "commu_helper/ClassifiedObject";
  }

  static const char* value(const ::commu_helper::ClassifiedObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::commu_helper::ClassifiedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A message representing an object that was classified using caffe.\n\
Header header\n\
\n\
# The certainty of the classification from 0 to 1\n\
float64 score\n\
\n\
# The label attached to this object\n\
std_msgs/String label\n\
\n\
# The bounding box for the classified object\n\
BoundingBox bbox\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
\n\
================================================================================\n\
MSG: commu_helper/BoundingBox\n\
# A simple 2d bounding box message\n\
\n\
float64 x_min\n\
float64 y_min\n\
float64 x_size\n\
float64 y_size\n\
";
  }

  static const char* value(const ::commu_helper::ClassifiedObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::commu_helper::ClassifiedObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.score);
      stream.next(m.label);
      stream.next(m.bbox);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClassifiedObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::commu_helper::ClassifiedObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::commu_helper::ClassifiedObject_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "score: ";
    Printer<double>::stream(s, indent + "  ", v.score);
    s << indent << "label: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.label);
    s << indent << "bbox: ";
    s << std::endl;
    Printer< ::commu_helper::BoundingBox_<ContainerAllocator> >::stream(s, indent + "  ", v.bbox);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMU_HELPER_MESSAGE_CLASSIFIEDOBJECT_H
