(cl:defpackage button_input-srv
  (:use )
  (:export
   "BINARYBUTTONINPUT"
   "<BINARYBUTTONINPUT-REQUEST>"
   "BINARYBUTTONINPUT-REQUEST"
   "<BINARYBUTTONINPUT-RESPONSE>"
   "BINARYBUTTONINPUT-RESPONSE"
  ))

