// Generated by gencpp from file look_helper/SetLookAtTargetResponse.msg
// DO NOT EDIT!


#ifndef LOOK_HELPER_MESSAGE_SETLOOKATTARGETRESPONSE_H
#define LOOK_HELPER_MESSAGE_SETLOOKATTARGETRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace look_helper
{
template <class ContainerAllocator>
struct SetLookAtTargetResponse_
{
  typedef SetLookAtTargetResponse_<ContainerAllocator> Type;

  SetLookAtTargetResponse_()
    : success(false)  {
    }
  SetLookAtTargetResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;




  typedef boost::shared_ptr< ::look_helper::SetLookAtTargetResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::look_helper::SetLookAtTargetResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetLookAtTargetResponse_

typedef ::look_helper::SetLookAtTargetResponse_<std::allocator<void> > SetLookAtTargetResponse;

typedef boost::shared_ptr< ::look_helper::SetLookAtTargetResponse > SetLookAtTargetResponsePtr;
typedef boost::shared_ptr< ::look_helper::SetLookAtTargetResponse const> SetLookAtTargetResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::look_helper::SetLookAtTargetResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::look_helper::SetLookAtTargetResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace look_helper

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::look_helper::SetLookAtTargetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::look_helper::SetLookAtTargetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::look_helper::SetLookAtTargetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::look_helper::SetLookAtTargetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::look_helper::SetLookAtTargetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::look_helper::SetLookAtTargetResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::look_helper::SetLookAtTargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::look_helper::SetLookAtTargetResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::look_helper::SetLookAtTargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "look_helper/SetLookAtTargetResponse";
  }

  static const char* value(const ::look_helper::SetLookAtTargetResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::look_helper::SetLookAtTargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
bool success\n\
";
  }

  static const char* value(const ::look_helper::SetLookAtTargetResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::look_helper::SetLookAtTargetResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SetLookAtTargetResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::look_helper::SetLookAtTargetResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::look_helper::SetLookAtTargetResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOOK_HELPER_MESSAGE_SETLOOKATTARGETRESPONSE_H
