// Generated by gencpp from file look_helper/SetLookAtTargetRequest.msg
// DO NOT EDIT!


#ifndef LOOK_HELPER_MESSAGE_SETLOOKATTARGETREQUEST_H
#define LOOK_HELPER_MESSAGE_SETLOOKATTARGETREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace look_helper
{
template <class ContainerAllocator>
struct SetLookAtTargetRequest_
{
  typedef SetLookAtTargetRequest_<ContainerAllocator> Type;

  SetLookAtTargetRequest_()
    : target_frame_name()  {
    }
  SetLookAtTargetRequest_(const ContainerAllocator& _alloc)
    : target_frame_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _target_frame_name_type;
  _target_frame_name_type target_frame_name;




  typedef boost::shared_ptr< ::look_helper::SetLookAtTargetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::look_helper::SetLookAtTargetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetLookAtTargetRequest_

typedef ::look_helper::SetLookAtTargetRequest_<std::allocator<void> > SetLookAtTargetRequest;

typedef boost::shared_ptr< ::look_helper::SetLookAtTargetRequest > SetLookAtTargetRequestPtr;
typedef boost::shared_ptr< ::look_helper::SetLookAtTargetRequest const> SetLookAtTargetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::look_helper::SetLookAtTargetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::look_helper::SetLookAtTargetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace look_helper

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::look_helper::SetLookAtTargetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::look_helper::SetLookAtTargetRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::look_helper::SetLookAtTargetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::look_helper::SetLookAtTargetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::look_helper::SetLookAtTargetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::look_helper::SetLookAtTargetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::look_helper::SetLookAtTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f035c613d0c3285d785da141558423bb";
  }

  static const char* value(const ::look_helper::SetLookAtTargetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf035c613d0c3285dULL;
  static const uint64_t static_value2 = 0x785da141558423bbULL;
};

template<class ContainerAllocator>
struct DataType< ::look_helper::SetLookAtTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "look_helper/SetLookAtTargetRequest";
  }

  static const char* value(const ::look_helper::SetLookAtTargetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::look_helper::SetLookAtTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
string target_frame_name\n\
\n\
";
  }

  static const char* value(const ::look_helper::SetLookAtTargetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::look_helper::SetLookAtTargetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_frame_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SetLookAtTargetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::look_helper::SetLookAtTargetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::look_helper::SetLookAtTargetRequest_<ContainerAllocator>& v)
  {
    s << indent << "target_frame_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.target_frame_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOOK_HELPER_MESSAGE_SETLOOKATTARGETREQUEST_H
