// Generated by gencpp from file button_input/BinaryButtonInputResponse.msg
// DO NOT EDIT!


#ifndef BUTTON_INPUT_MESSAGE_BINARYBUTTONINPUTRESPONSE_H
#define BUTTON_INPUT_MESSAGE_BINARYBUTTONINPUTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace button_input
{
template <class ContainerAllocator>
struct BinaryButtonInputResponse_
{
  typedef BinaryButtonInputResponse_<ContainerAllocator> Type;

  BinaryButtonInputResponse_()
    : response(0)  {
    }
  BinaryButtonInputResponse_(const ContainerAllocator& _alloc)
    : response(0)  {
  (void)_alloc;
    }



   typedef uint8_t _response_type;
  _response_type response;




  typedef boost::shared_ptr< ::button_input::BinaryButtonInputResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::button_input::BinaryButtonInputResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BinaryButtonInputResponse_

typedef ::button_input::BinaryButtonInputResponse_<std::allocator<void> > BinaryButtonInputResponse;

typedef boost::shared_ptr< ::button_input::BinaryButtonInputResponse > BinaryButtonInputResponsePtr;
typedef boost::shared_ptr< ::button_input::BinaryButtonInputResponse const> BinaryButtonInputResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::button_input::BinaryButtonInputResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::button_input::BinaryButtonInputResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace button_input

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::button_input::BinaryButtonInputResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::button_input::BinaryButtonInputResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::button_input::BinaryButtonInputResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::button_input::BinaryButtonInputResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::button_input::BinaryButtonInputResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::button_input::BinaryButtonInputResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::button_input::BinaryButtonInputResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59064532f110d857c53f36f4ab7ad30a";
  }

  static const char* value(const ::button_input::BinaryButtonInputResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59064532f110d857ULL;
  static const uint64_t static_value2 = 0xc53f36f4ab7ad30aULL;
};

template<class ContainerAllocator>
struct DataType< ::button_input::BinaryButtonInputResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "button_input/BinaryButtonInputResponse";
  }

  static const char* value(const ::button_input::BinaryButtonInputResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::button_input::BinaryButtonInputResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 response\n\
";
  }

  static const char* value(const ::button_input::BinaryButtonInputResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::button_input::BinaryButtonInputResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BinaryButtonInputResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::button_input::BinaryButtonInputResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::button_input::BinaryButtonInputResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BUTTON_INPUT_MESSAGE_BINARYBUTTONINPUTRESPONSE_H
