// Generated by gencpp from file button_input/BinaryButtonInput.msg
// DO NOT EDIT!


#ifndef BUTTON_INPUT_MESSAGE_BINARYBUTTONINPUT_H
#define BUTTON_INPUT_MESSAGE_BINARYBUTTONINPUT_H

#include <ros/service_traits.h>


#include <button_input/BinaryButtonInputRequest.h>
#include <button_input/BinaryButtonInputResponse.h>


namespace button_input
{

struct BinaryButtonInput
{

typedef BinaryButtonInputRequest Request;
typedef BinaryButtonInputResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BinaryButtonInput
} // namespace button_input


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::button_input::BinaryButtonInput > {
  static const char* value()
  {
    return "59064532f110d857c53f36f4ab7ad30a";
  }

  static const char* value(const ::button_input::BinaryButtonInput&) { return value(); }
};

template<>
struct DataType< ::button_input::BinaryButtonInput > {
  static const char* value()
  {
    return "button_input/BinaryButtonInput";
  }

  static const char* value(const ::button_input::BinaryButtonInput&) { return value(); }
};


// service_traits::MD5Sum< ::button_input::BinaryButtonInputRequest> should match 
// service_traits::MD5Sum< ::button_input::BinaryButtonInput > 
template<>
struct MD5Sum< ::button_input::BinaryButtonInputRequest>
{
  static const char* value()
  {
    return MD5Sum< ::button_input::BinaryButtonInput >::value();
  }
  static const char* value(const ::button_input::BinaryButtonInputRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::button_input::BinaryButtonInputRequest> should match 
// service_traits::DataType< ::button_input::BinaryButtonInput > 
template<>
struct DataType< ::button_input::BinaryButtonInputRequest>
{
  static const char* value()
  {
    return DataType< ::button_input::BinaryButtonInput >::value();
  }
  static const char* value(const ::button_input::BinaryButtonInputRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::button_input::BinaryButtonInputResponse> should match 
// service_traits::MD5Sum< ::button_input::BinaryButtonInput > 
template<>
struct MD5Sum< ::button_input::BinaryButtonInputResponse>
{
  static const char* value()
  {
    return MD5Sum< ::button_input::BinaryButtonInput >::value();
  }
  static const char* value(const ::button_input::BinaryButtonInputResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::button_input::BinaryButtonInputResponse> should match 
// service_traits::DataType< ::button_input::BinaryButtonInput > 
template<>
struct DataType< ::button_input::BinaryButtonInputResponse>
{
  static const char* value()
  {
    return DataType< ::button_input::BinaryButtonInput >::value();
  }
  static const char* value(const ::button_input::BinaryButtonInputResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BUTTON_INPUT_MESSAGE_BINARYBUTTONINPUT_H
