// Generated by gencpp from file button_input/BinaryButtonInputRequest.msg
// DO NOT EDIT!


#ifndef BUTTON_INPUT_MESSAGE_BINARYBUTTONINPUTREQUEST_H
#define BUTTON_INPUT_MESSAGE_BINARYBUTTONINPUTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace button_input
{
template <class ContainerAllocator>
struct BinaryButtonInputRequest_
{
  typedef BinaryButtonInputRequest_<ContainerAllocator> Type;

  BinaryButtonInputRequest_()
    {
    }
  BinaryButtonInputRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::button_input::BinaryButtonInputRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::button_input::BinaryButtonInputRequest_<ContainerAllocator> const> ConstPtr;

}; // struct BinaryButtonInputRequest_

typedef ::button_input::BinaryButtonInputRequest_<std::allocator<void> > BinaryButtonInputRequest;

typedef boost::shared_ptr< ::button_input::BinaryButtonInputRequest > BinaryButtonInputRequestPtr;
typedef boost::shared_ptr< ::button_input::BinaryButtonInputRequest const> BinaryButtonInputRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::button_input::BinaryButtonInputRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::button_input::BinaryButtonInputRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace button_input

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::button_input::BinaryButtonInputRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::button_input::BinaryButtonInputRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::button_input::BinaryButtonInputRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::button_input::BinaryButtonInputRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::button_input::BinaryButtonInputRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::button_input::BinaryButtonInputRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::button_input::BinaryButtonInputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::button_input::BinaryButtonInputRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::button_input::BinaryButtonInputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "button_input/BinaryButtonInputRequest";
  }

  static const char* value(const ::button_input::BinaryButtonInputRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::button_input::BinaryButtonInputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::button_input::BinaryButtonInputRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::button_input::BinaryButtonInputRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BinaryButtonInputRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::button_input::BinaryButtonInputRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::button_input::BinaryButtonInputRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // BUTTON_INPUT_MESSAGE_BINARYBUTTONINPUTREQUEST_H
